version: '3.8'

services:
  # PDF Processor - Production
  pdf-processor:
    build:
      context: ./services/pdf-processor
      dockerfile: Dockerfile
    environment:
      - PORT=3095
      - DEBUG=false
      - PYTHONUNBUFFERED=1
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Admin Backend - Production
  admin-backend:
    build:
      context: ./services/admin-backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # User Backend - Production
  user-backend:
    build:
      context: ./services/user-backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Admin Frontend - Production
  admin-frontend:
    build:
      context: ./apps/admin-frontend
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production

  # Mobile Frontend - Production
  mobile-frontend:
    build:
      context: ./apps/mobile-frontend
      dockerfile: Dockerfile
      target: production
    environment:
      - NODE_ENV=production

  # Use external MinIO or cloud storage in production
  minio:
    profiles:
      - development
