services:
  # PDF Processor - Python service for PDF analysis and image extraction
  pdf-processor:
    build:
      context: ./services/pdf-processor
      dockerfile: Dockerfile
    ports:
      - "3095:3095"
    environment:
      - PORT=3095
      - DEBUG=false
      - PYTHONUNBUFFERED=1
    volumes:
      - ./example-files:/app/example-files:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request, sys; urllib.request.urlopen('http://localhost:3095/health'); print('OK')"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

  # Admin Backend - Express TypeScript API for admin operations
  admin-backend:
    build:
      context: ./services/admin-backend
      dockerfile: Dockerfile
    ports:
      - "3091:3091"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - PORT=3091
      - PDF_PROCESSOR_URL=http://pdf-processor:3095
      - CORS_ORIGINS=http://localhost:8091
      - DATABASE_NAME=dehn
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_BUCKET_PRIVATE=dehn-private
      - MINIO_BUCKET_PUBLIC=dehn-public
      - MINIO_ACCESS_KEY=dehn-access-key
      - MINIO_SECRET_KEY=dehn-secret-key
      - MINIO_USE_SSL=false
    depends_on:
      - pdf-processor
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3091/health"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3

  # User Backend - Express TypeScript API for user operations
  user-backend:
    build:
      context: ./services/user-backend
      dockerfile: Dockerfile
    ports:
      - "3090:3090"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - PORT=3090
      - PDF_PROCESSOR_URL=http://pdf-processor:3095
      - CORS_ORIGINS=http://localhost:8090
      - DATABASE_NAME=dehn
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_BUCKET_PRIVATE=dehn-private
      - MINIO_BUCKET_PUBLIC=dehn-public
      - MINIO_ACCESS_KEY=dehn-access-key
      - MINIO_SECRET_KEY=dehn-secret-key
      - MINIO_USE_SSL=false
    depends_on:
      - pdf-processor
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3090/health"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3

  # MinIO - S3-compatible storage for development
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      - MINIO_ROOT_USER=dehn-access-key
      - MINIO_ROOT_PASSWORD=dehn-secret-key
      - MINIO_DEFAULT_BUCKETS=dehn-public:public,dehn-private:none
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
