services:
  # PDF Processor - Development overrides
  pdf-processor:
    build:
      context: ./services/pdf-processor
      dockerfile: Dockerfile
    volumes:
      - ./services/pdf-processor:/app
      - ./example-files:/app/example-files:ro
    environment:
      - DEBUG=true
      - DEVELOPMENT=true
      - PYTHONUNBUFFERED=1
    command: python run-dev.py

  # Admin Backend - Development overrides
  admin-backend:
    build:
      context: ./services/admin-backend
      dockerfile: Dockerfile
    volumes:
      - ./services/admin-backend/src:/app/src
    environment:
      - NODE_ENV=development
      - DEBUG=true
    command: npm run dev

  # User Backend - Development overrides
  user-backend:
    build:
      context: ./services/user-backend
      dockerfile: Dockerfile
    volumes:
      - ./services/user-backend/src:/app/src
    environment:
      - NODE_ENV=development
      - DEBUG=true
    command: npm run dev
