services:
  # PDF Processor Service
  pdf-processor:
    build:
      context: ./services/pdf-processor
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./example-files:/app/example-files:ro
      - pdf_storage:/app/storage
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DEBUG=false
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=dehn-access-key
      - S3_SECRET_KEY=dehn-secret-key
      - S3_BUCKET_NAME=pdf-documents
      - MONGODB_URI=mongodb+srv://your-username:your-password@your-cluster.mongodb.net/dehn?retryWrites=true&w=majority
    depends_on:
      - minio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Admin Backend Service
  admin-backend:
    build:
      context: ./services/admin-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://your-username:your-password@your-cluster.mongodb.net/dehn?retryWrites=true&w=majority
      - JWT_SECRET=your-jwt-secret-here
      - PDF_PROCESSOR_URL=http://pdf-processor:8080
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=dehn-access-key
      - S3_SECRET_KEY=dehn-secret-key
      - S3_BUCKET_NAME=pdf-documents
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000
    depends_on:
      - pdf-processor
      - minio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # User Backend Service
  user-backend:
    build:
      context: ./services/user-backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://your-username:your-password@your-cluster.mongodb.net/dehn?retryWrites=true&w=majority
      - JWT_SECRET=your-jwt-secret-here
      - PDF_PROCESSOR_URL=http://pdf-processor:8080
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=dehn-access-key
      - S3_SECRET_KEY=dehn-secret-key
      - S3_BUCKET_NAME=pdf-documents
      - CORS_ORIGINS=http://localhost:5174,http://localhost:3000
    depends_on:
      - pdf-processor
      - minio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Admin Frontend
  admin-frontend:
    build:
      context: ./apps/admin-frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./apps/admin-frontend/src:/app/src
      - ./apps/admin-frontend/public:/app/public
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_PDF_PROCESSOR_URL=http://localhost:8080
    depends_on:
      - admin-backend
    restart: unless-stopped

  # Mobile Frontend
  mobile-frontend:
    build:
      context: ./apps/mobile-frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "5174:5174"
    volumes:
      - ./apps/mobile-frontend/src:/app/src
      - ./apps/mobile-frontend/public:/app/public
    environment:
      - VITE_API_URL=http://localhost:3002
      - VITE_PDF_PROCESSOR_URL=http://localhost:8080
    depends_on:
      - user-backend
    restart: unless-stopped

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=dehn-access-key
      - MINIO_ROOT_PASSWORD=dehn-secret-key
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO Client (for bucket creation)
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=dehn-access-key
      - MINIO_SECRET_KEY=dehn-secret-key
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc config host add myminio http://minio:9000 dehn-access-key dehn-secret-key; do
        echo 'Waiting for MinIO to be ready...'
        sleep 2
      done;
      /usr/bin/mc mb myminio/pdf-documents || true;
      /usr/bin/mc policy set public myminio/pdf-documents || true;
      echo 'MinIO buckets created successfully'
      "
    restart: "no"

  # Redis (for caching)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  minio_data:
    driver: local
  redis_data:
    driver: local
  pdf_storage:
    driver: local

networks:
  default:
    name: dehn-network
