services:
  # PDF Processor - Development overrides
  pdf-processor:
    build:
      context: ./services/pdf-processor
      dockerfile: Dockerfile
    volumes:
      - ./services/pdf-processor:/app
      - ./example-files:/app/example-files:ro
      - ./google-credentials.json:/app/google-credentials.json:ro
    environment:
      - DEBUG=true
      - DEVELOPMENT=true
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
      - GOOGLE_CLOUD_PROJECT=servusai-468510
    command: python run-dev.py

  # Admin Backend - Development overrides
  admin-backend:
    build:
      context: ./services/admin-backend
      dockerfile: Dockerfile
    volumes:
      - ./services/admin-backend/src:/app/src
      - ./google-credentials.json:/app/google-credentials.json:ro
    environment:
      - NODE_ENV=development
      - DEBUG=true
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
      - GOOGLE_CLOUD_PROJECT=servusai-468510
      - GCS_BUCKET_NAME=dehn-documents-servusai-468510-dev
    command: npm run dev

  # User Backend - Development overrides
  user-backend:
    build:
      context: ./services/user-backend
      dockerfile: Dockerfile
    volumes:
      - ./services/user-backend/src:/app/src
      - ./google-credentials.json:/app/google-credentials.json:ro
    environment:
      - NODE_ENV=development
      - DEBUG=true
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
      - GOOGLE_CLOUD_PROJECT=servusai-468510
      - GCS_BUCKET_NAME=dehn-documents-servusai-468510-dev
    command: npm run dev
